apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sshportal.fullname" . }}-secrets
  labels:
    {{- include "sshportal.labels" . | nindent 4 }}
stringData:
  {{- if .Values.inviteToken }}
  invite-token: {{ .Values.inviteToken | quote }}
  {{- else }}
  invite-token: {{ randAlphaNum 16 | quote }}
  {{- end }}

  {{- if .Values.mysql.enabled }}
  mysql-connection: {{ .Values.mysql.auth.username }}:{{ .Values.mysql.auth.password }}@tcp({{ .Values.mysql.hostname }}:{{ .Values.mysql.port }})/{{ .Values.mysql.auth.database }}?charset=utf8&parseTime=true&loc=Local
  {{- else }}
  mysql-connection: ""
  {{- end }}
