apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "librenms.fullname" . }}-dispatcher
  labels:
    {{- include "librenms.dispatcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dispatcher.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "librenms.dispatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dispatcher.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "librenms.dispatcher.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "librenms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dispatcher.podSecurityContext | nindent 8 }}
      containers:
        - name: dispatcher
          securityContext:
            {{- toYaml .Values.dispatcher.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{ include "librenms.environment_default" . | nindent 12 }}
            - name: SIDECAR_DISPATCHER
              value: "1"
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DISPATCHER_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CACHE_DRIVER
              value: "redis"
          resources:
            {{- toYaml .Values.dispatcher.resources | nindent 12 }}
          volumeMounts:
            - name: librenms-data
              mountPath: /data
      volumes:
        - name: librenms-data
      {{- with .Values.dispatcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
