{{- define "librenms.dispatcher_env" }}
- name: SIDECAR_DISPATCHER
  value: "1"
- name: NODE_ID
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: DISPATCHER_NODE_ID
  valueFrom:
    fieldRef:
      fieldPath: metadata.name
- name: CACHE_DRIVER
  value: {{ default "redis" .Values.dispatcher.cacheDriver | quote }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "librenms.fullname" . }}-dispatcher
  labels:
    {{- include "librenms.dispatcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dispatcher.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "librenms.dispatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dispatcher.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "librenms.dispatcher.labels" . | nindent 8 }}
    spec:
      {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "librenms.dispatcher.selectorLabels" . | nindent 14 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "librenms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dispatcher.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - sh
            - '-c'
            - >-
                until nc -z {{ include "librenms.fullname" . }} {{ .Values.app.service.port }}; do
                  echo waiting for librenms;
                  sleep 2;
                done
        - name: init-env
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - sh
            - '-c'
            - |
                export | cut -d' ' -f2 | tr -d "'"  > /data/.env
          envFrom:
            {{- include "librenms.environment_ref_default" . | nindent 12 }}
          env:
            {{- include "librenms.dispatcher_env" . | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      containers:
        - name: dispatcher
          securityContext:
            {{- toYaml .Values.dispatcher.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- include "librenms.environment_ref_default" . | nindent 12 }}
          env:
            {{- include "librenms.dispatcher_env" . | nindent 12 }}
          resources:
            {{- toYaml .Values.dispatcher.resources | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - >
                      mysql -h ${DB_HOST} -u ${DB_USER} --password=${DB_PASSWORD} ${DB_NAME} -e
                      "DELETE FROM poller_cluster WHERE node_id = '${DISPATCHER_NODE_ID}';"
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /opt/librenms/config.php
              subPath: config.php
      volumes:
        - name: data
        - name: config
          configMap:
            name: {{ include "librenms.fullname" . }}-config
      {{- with .Values.dispatcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dispatcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
