apiVersion: v1
kind: Service
metadata:
  name: {{ include "librenms.fullname" . }}
  labels:
    {{- include "librenms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 515
      targetPort: syslog-tcp
      protocol: TCP
      name: syslog-tcp
    - port: 514
      targetPort: syslog-udp
      protocol: UDP
      name: syslog
  selector:
    {{- include "librenms.selectorLabels" . | nindent 4 }}
