apiVersion: v1
kind: Service
metadata:
  name: {{ include "librenms.fullname" . }}
  labels:
    {{- include "librenms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "librenms.selectorLabels" . | nindent 4 }}
