apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "librenms.fullname" . }}-rrdcached
  labels:
    {{- include "librenms.rrdcached.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rrdcached.replicaCount }}
  serviceName: {{ include "librenms.fullname" . }}-rrdcached
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "librenms.rrdcached.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.rrdcached.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "librenms.rrdcached.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "librenms.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.rrdcached.podSecurityContext | nindent 8 }}
      containers:
        - name: rrdcached
          securityContext:
            {{- toYaml .Values.rrdcached.securityContext | nindent 12 }}
          image: {{ .Values.rrdcached.image.repository }}:{{ .Values.rrdcached.image.tag | default "latest" }}
          imagePullPolicy: {{ .Values.rrdcached.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "librenms.fullname" . }}-rrdcached
          ports:
            - name: rrd
              containerPort: 42217
              protocol: TCP
          livenessProbe: &rrd_tcpProbe
            tcpSocket:
              port: rrd
          readinessProbe: *rrd_tcpProbe
          resources:
            {{- toYaml .Values.rrdcached.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
      {{- with .Values.rrdcached.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rrdcached.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rrdcached.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
