{{- $secretName := printf "%s-%s" (include "sshportal.fullname" .) "secrets" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "sshportal.labels" . | nindent 4 }}

{{- $secret := lookup "v1" "Secret" .Release.Namespace $secretName -}}
{{- if $secret }}
{{- with $secret.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- else }}
stringData:
  {{- if .Values.inviteToken }}
  invite-token: {{ .Values.inviteToken | quote }}
  {{- else }}
  invite-token: {{ randAlphaNum 16 | quote }}
  {{- end }}

  {{- if .Values.mysql.enabled }}
  mysql-connection: {{ .Values.mysql.auth.username }}:{{ .Values.mysql.auth.password }}@tcp({{ .Values.mysql.hostname }}:{{ .Values.mysql.port }})/{{ .Values.mysql.auth.database }}?charset=utf8&parseTime=true&loc=Local
  {{- else }}
  mysql-connection: ""
  {{- end }}
{{- end }}
