apiVersion: v1
kind: Service
metadata:
  name: {{ include "librenms.fullname" . }}-syslog
  labels:
    {{- include "librenms.syslog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.syslog.service.type }}
  ports:
    - name: syslog-tcp
      port: {{ .Values.syslog.service.ports.tcp }}
      targetPort: syslog-tcp
      protocol: TCP
      {{- if (eq .Values.syslog.service.type "ClusterIP") }}
      nodePort: null
      {{- end }}
    - name: syslog
      port: {{ .Values.syslog.service.ports.udp }}
      targetPort: syslog-udp
      protocol: UDP
      {{- if (eq .Values.syslog.service.type "ClusterIP") }}
      nodePort: null
      {{- end }}
  selector:
    {{- include "librenms.syslog.selectorLabels" . | nindent 4 }}
